// ===== Multi-language Support for Coffee Market =====
var TRANSLATIONS = {
    ar: {
        dir: 'rtl',
        // Navbar
        navProducts: 'المنتجات',
        navAbout: 'من نحن',
        navDelivery: 'التوصيل',
        navContact: 'تواصل معنا',
        searchPlaceholder: 'ابحث عن منتج...',
        searchPlaceholderLong: 'ابحث عن منتج، ماركة، أو فئة...',
        // Hero
        heroSubtitle: 'أجود أنواع القهوة والمشروبات الساخنة',
        heroTagline: 'من نابلس إلى بيتك.. نوصّلك طعم القهوة الأصيل',
        aboutText: 'سوق القهوه - وجهتك لأفضل أنواع القهوة العربية والتركية والإسبريسو.\nنقدم لكم تشكيلة واسعة من حبوب القهوة الطازجة والمطحونة،\nبالإضافة إلى أدوات تحضير القهوة وإكسسواراتها.\nزورونا في نابلس أو اطلبوا أونلاين.',
        shopNow: 'تسوق الآن',
        // Products
        ourProducts: 'منتجاتنا',
        filterAll: 'الكل',
        filterSpecial: 'مميز',
        filterBestseller: 'الأكثر مبيعاً',
        filterBtn: 'فلتر ▼',
        categoryLabel: 'النوع',
        loading: 'جاري تحميل تشكيلتنا الفاخرة...',
        addToCart: 'أضف للسلة',
        customPackageTitle: 'صممي علبتك المخصصة',
        add: 'أضف',
        soldOut: 'نفذت الكمية',
        added: 'تمت الإضافة',
        sizeLabel: 'الحجم:',
        qtyLabel: 'الكمية:',
        relatedProducts: 'منتجات مشابهة',
        // Cart
        cart: 'سلة التسوق',
        cartEmpty: 'السلة فارغة',
        cartTotal: 'المجموع:',
        checkout: 'إتمام الطلب',
        clearCart: 'تفريغ السلة',
        // About
        aboutUs: 'من نحن',
        featureQuality: 'جودة عالية مضمونة',
        featureFast: 'توصيل سريع',
        featurePrice: 'أسعار منافسة',
        featurePackaging: 'تغليف مميز',
        featureService: 'خدمة عملاء مميزة',
        // Delivery
        deliveryTitle: 'مناطق التوصيل',
        deliveryWestBank: 'الضفة',
        deliveryWestBankDesc: '₪20 لجميع المدن والبلدات',
        deliveryJerusalem: 'القدس',
        deliveryJerusalemDesc: '₪30 مع خدمة توصيل سريعة',
        deliveryInside: 'الداخل',
        deliveryInsideDesc: '₪50 تغليف وتوصيل آمن',
        // Contact
        contactTitle: 'تواصل معنا',
        contactSubtitle: 'للطلب أو الاستفسار',
        // Footer
        footerRights: '© 2026 سوق القهوه. جميع الحقوق محفوظة',
        // Checkout
        backToShopping: '→ العودة للتسوق',
        home: '← الرئيسية',
        checkoutTitle: 'إتمام الطلب',
        loadingOrder: 'جاري تحميل بيانات الطلب...',
        emptyCart: 'السلة فارغة! أضف منتجات أولاً',
        productsCount: 'المنتجات',
        pieces: 'قطعة',
        deliveryMethod: 'طريقة الاستلام',
        pickupOption: 'استلام ذاتي (مجاني)',
        pickupDesc: 'استلمي طلبك بنفسك بدون تكلفة إضافية',
        deliveryOption: 'توصيل للعنوان',
        deliveryDesc: 'توصيل لجميع مناطق الضفة، القدس، والداخل',
        selectRegion: 'اختاري المنطقة:',
        westbank: 'الضفة',
        jerusalem: 'القدس',
        inside: 'الداخل',
        contactInfo: 'معلومات التواصل',
        nameLabel: 'الاسم',
        namePlaceholder: 'اسمك الكريم',
        phoneLabel: 'رقم الهاتف',
        phonePlaceholder: '05xxxxxxxx',
        addressLabel: 'العنوان (المدينة + تفاصيل)',
        addressPlaceholder: 'المدينة، الحي، الشارع...',
        notesLabel: 'ملاحظات إضافية (اختياري)',
        notesPlaceholder: 'أي ملاحظات على الطلب...',
        orderSummary: 'ملخص الطلب',
        itemsCount: 'عدد المنتجات:',
        subtotal: 'المجموع الفرعي:',
        deliveryFee: 'التوصيل:',
        total: 'المجموع:',
        free: 'مجاني',
        saveOrder: 'حفظ الطلب',
        newOrderMsg: 'مرحبا، طلب جديد',
        savingOrder: 'جاري حفظ الطلب...',
        // Checkout validation
        enterName: 'يرجى إدخال الاسم',
        enterPhone: 'يرجى إدخال رقم الهاتف',
        selectRegionError: 'يرجى اختيار المنطقة',
        enterAddress: 'يرجى إدخال العنوان',
        stockError: 'بعض المنتجات غير متوفرة حالياً:',
        productUnavailable: 'منتج غير متوفر',
        productUnavailable: 'منتج غير متوفر',
        // Confirmation
        orderConfirmed: 'تم تأكيد طلبك بنجاح',
        orderNumber: 'رقم الطلب:',
        copy: 'نسخ',
        orderDetails: 'تفاصيل الطلب',
        productCount: 'عدد المنتجات:',
        deliveryMethodLabel: 'طريقة الاستلام:',
        pickup: 'استلام ذاتي',
        delivery: 'توصيل',
        willContact: 'سيتم التواصل معك قريباً لتأكيد الطلب',
        sendWhatsapp: 'إرسال الطلب عبر واتساب',
        continueShopping: 'متابعة التسوق',
        nameField: 'الاسم:',
        phoneField: 'الهاتف:',
        addressField: 'العنوان:',
        notesField: 'ملاحظات:',
        dateField: 'التاريخ:',
        priceTBD: 'يحدد لاحقاً',
        // Discount
        discount: 'خصم'
    },
    en: {
        dir: 'ltr',
        navProducts: 'Products',
        navAbout: 'About',
        navDelivery: 'Delivery',
        navContact: 'Contact',
        searchPlaceholder: 'Search for a product...',
        searchPlaceholderLong: 'Search by product, brand, or category...',
        heroSubtitle: 'The finest coffee & hot beverages',
        heroTagline: 'From Nablus to your door — authentic coffee taste',
        shopNow: 'Shop Now',
        ourProducts: 'Our Products',
        filterAll: 'All',
        filterSpecial: 'Special',
        filterBestseller: 'Bestseller',
        filterBtn: 'Filter ▼',
        categoryLabel: 'Category',
        loading: 'Loading our collection...',
        addToCart: 'Add to Cart',
        customPackageTitle: 'Design Your Custom Box',
        add: 'Add',
        soldOut: 'Sold Out',
        added: 'Added',
        sizeLabel: 'Size:',
        qtyLabel: 'Quantity:',
        relatedProducts: 'Related Products',
        cart: 'Shopping Cart',
        cartEmpty: 'Cart is empty',
        cartTotal: 'Total:',
        checkout: 'Checkout',
        clearCart: 'Clear Cart',
        aboutUs: 'About Us',
        featureQuality: 'Guaranteed Quality',
        featureFast: 'Fast Delivery',
        featurePrice: 'Competitive Prices',
        featurePackaging: 'Premium Packaging',
        featureService: 'Excellent Service',
        deliveryTitle: 'Delivery Areas',
        deliveryWestBank: 'West Bank',
        deliveryWestBankDesc: '₪20 for all cities',
        deliveryJerusalem: 'Jerusalem',
        deliveryJerusalemDesc: '₪30 with fast delivery',
        deliveryInside: 'Inside (48)',
        deliveryInsideDesc: '₪50 safe packaging & delivery',
        contactTitle: 'Contact Us',
        contactSubtitle: 'For orders or inquiries',
        footerRights: '© 2026 Coffee Market. All rights reserved',
        backToShopping: '← Back to Shopping',
        home: '← Home',
        checkoutTitle: 'Checkout',
        loadingOrder: 'Loading order details...',
        emptyCart: 'Cart is empty! Add products first',
        productsCount: 'Products',
        pieces: 'pcs',
        deliveryMethod: 'Delivery Method',
        pickupOption: 'Pickup (Free)',
        pickupDesc: 'Pick up your order at no extra cost',
        deliveryOption: 'Delivery to Address',
        deliveryDesc: 'Delivery to West Bank, Jerusalem & Inside',
        selectRegion: 'Select Region:',
        westbank: 'West Bank',
        jerusalem: 'Jerusalem',
        inside: 'Inside (48)',
        contactInfo: 'Contact Information',
        nameLabel: 'Name',
        namePlaceholder: 'Your full name',
        phoneLabel: 'Phone Number',
        phonePlaceholder: '05xxxxxxxx',
        addressLabel: 'Address (city + details)',
        addressPlaceholder: 'City, neighborhood, street...',
        notesLabel: 'Additional Notes (optional)',
        notesPlaceholder: 'Any notes for the order...',
        orderSummary: 'Order Summary',
        itemsCount: 'Items:',
        subtotal: 'Subtotal:',
        deliveryFee: 'Delivery:',
        total: 'Total:',
        free: 'Free',
        saveOrder: 'Save Order',
        newOrderMsg: 'Hello, new order',
        savingOrder: 'Saving order...',
        enterName: 'Please enter your name',
        enterPhone: 'Please enter your phone number',
        selectRegionError: 'Please select a region',
        enterAddress: 'Please enter your address',
        stockError: 'Some products are currently unavailable:',
        productUnavailable: 'منتج غير متوفر',
        orderConfirmed: 'Your order has been confirmed!',
        orderNumber: 'Order #:',
        copy: 'Copy',
        orderDetails: 'Order Details',
        productCount: 'Items:',
        deliveryMethodLabel: 'Delivery:',
        pickup: 'Pickup',
        delivery: 'Delivery',
        willContact: 'We will contact you soon to confirm the order',
        sendWhatsapp: 'Send Order via WhatsApp',
        continueShopping: 'Continue Shopping',
        nameField: 'Name:',
        phoneField: 'Phone:',
        addressField: 'Address:',
        notesField: 'Notes:',
        dateField: 'Date:',
        priceTBD: 'TBD',
        discount: 'OFF'
    },
    he: {
        dir: 'rtl',
        navProducts: 'מוצרים',
        navAbout: 'אודות',
        navDelivery: 'משלוח',
        navContact: 'צור קשר',
        searchPlaceholder: 'חפש מוצר...',
        searchPlaceholderLong: 'חפש מוצר, מותג או קטגוריה...',
        heroSubtitle: 'הקפה והמשקאות החמים הטובים ביותר',
        heroTagline: 'מנאבלוס עד אליך — טעם הקפה המקורי',
        shopNow: 'קנה עכשיו',
        ourProducts: 'המוצרים שלנו',
        filterAll: 'הכל',
        filterSpecial: 'מיוחד',
        filterBestseller: 'רב מכר',
        filterBtn: 'סינון ▼',
        categoryLabel: 'קטגוריה',
        loading: 'טוען את הקולקציה שלנו...',
        addToCart: 'הוסף לסל',
        customPackageTitle: 'עצב את הקופסה שלך',
        add: 'הוסף',
        soldOut: 'אזל מהמלאי',
        added: 'נוסף',
        sizeLabel: 'גודל:',
        qtyLabel: 'כמות:',
        relatedProducts: 'מוצרים דומים',
        cart: 'עגלת קניות',
        cartEmpty: 'העגלה ריקה',
        cartTotal: 'סה"כ:',
        checkout: 'לתשלום',
        clearCart: 'נקה עגלה',
        aboutUs: 'אודותינו',
        featureQuality: 'איכות מובטחת',
        featureFast: 'משלוח מהיר',
        featurePrice: 'מחירים תחרותיים',
        featurePackaging: 'אריזה מובחרת',
        featureService: 'שירות לקוחות מעולה',
        deliveryTitle: 'אזורי משלוח',
        deliveryWestBank: 'הגדה',
        deliveryWestBankDesc: '₪20 לכל הערים',
        deliveryJerusalem: 'ירושלים',
        deliveryJerusalemDesc: '₪30 עם משלוח מהיר',
        deliveryInside: 'פנים (48)',
        deliveryInsideDesc: '₪50 אריזה ומשלוח בטוחים',
        contactTitle: 'צור קשר',
        contactSubtitle: 'להזמנות או שאלות',
        footerRights: '© 2026 Coffee Market. כל הזכויות שמורות',
        backToShopping: '← חזרה לחנות',
        home: '← ראשי',
        checkoutTitle: 'תשלום',
        loadingOrder: 'טוען פרטי הזמנה...',
        emptyCart: 'העגלה ריקה! הוסף מוצרים קודם',
        productsCount: 'מוצרים',
        pieces: 'יח\'',
        deliveryMethod: 'אופן המשלוח',
        pickupOption: 'איסוף עצמי (חינם)',
        pickupDesc: 'אסוף את ההזמנה בעצמך ללא עלות נוספת',
        deliveryOption: 'משלוח לכתובת',
        deliveryDesc: 'משלוח לגדה, ירושלים והפנים',
        selectRegion: 'בחר אזור:',
        westbank: 'הגדה',
        jerusalem: 'ירושלים',
        inside: 'פנים (48)',
        contactInfo: 'פרטי התקשרות',
        nameLabel: 'שם',
        namePlaceholder: 'השם המלא שלך',
        phoneLabel: 'מספר טלפון',
        phonePlaceholder: '05xxxxxxxx',
        addressLabel: 'כתובת (עיר + פרטים)',
        addressPlaceholder: 'עיר, שכונה, רחוב...',
        notesLabel: 'הערות נוספות (אופציונלי)',
        notesPlaceholder: 'הערות להזמנה...',
        orderSummary: 'סיכום הזמנה',
        itemsCount: 'פריטים:',
        subtotal: 'סכום ביניים:',
        deliveryFee: 'משלוח:',
        total: 'סה"כ:',
        free: 'חינם',
        saveOrder: 'שמור הזמנה',
        newOrderMsg: 'שלום, הזמנה חדשה',
        savingOrder: 'שומר הזמנה...',
        enterName: 'אנא הזן שם',
        enterPhone: 'אנא הזן מספר טלפון',
        selectRegionError: 'אנא בחר אזור',
        enterAddress: 'אנא הזן כתובת',
        stockError: 'חלק מהמוצרים אינם זמינים כרגע:',
        productUnavailable: 'منتج غير متوفر',
        orderConfirmed: 'ההזמנה שלך אושרה בהצלחה!',
        orderNumber: 'מס\' הזמנה:',
        copy: 'העתק',
        orderDetails: 'פרטי הזמנה',
        productCount: 'פריטים:',
        deliveryMethodLabel: 'משלוח:',
        pickup: 'איסוף עצמי',
        delivery: 'משלוח',
        willContact: 'ניצור איתך קשר בקרוב לאישור ההזמנה',
        sendWhatsapp: 'שלח הזמנה בוואטסאפ',
        continueShopping: 'המשך קניות',
        nameField: 'שם:',
        phoneField: 'טלפון:',
        addressField: 'כתובת:',
        notesField: 'הערות:',
        dateField: 'תאריך:',
        priceTBD: 'ייקבע',
        discount: 'הנחה'
    }
};

var currentLang = localStorage.getItem('coffeemarket_lang') || 'ar';

function t(key) {
    return (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) || (TRANSLATIONS.ar[key]) || key;
}

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('coffeemarket_lang', lang);
    applyLanguage();
    // Re-render products if on main page
    if (typeof renderProducts === 'function') {
        renderProducts();
    }
}

function applyLanguage() {
    var tr = TRANSLATIONS[currentLang];
    document.documentElement.setAttribute('dir', tr.dir);
    document.documentElement.setAttribute('lang', currentLang);

    // Update lang switcher active state
    var btns = document.querySelectorAll('.lang-btn');
    for (var i = 0; i < btns.length; i++) {
        btns[i].classList.toggle('active', btns[i].getAttribute('data-lang') === currentLang);
    }

    // Update all elements with data-i18n attribute
    var elements = document.querySelectorAll('[data-i18n]');
    for (var i = 0; i < elements.length; i++) {
        var key = elements[i].getAttribute('data-i18n');
        if (elements[i].tagName === 'INPUT' || elements[i].tagName === 'TEXTAREA') {
            elements[i].placeholder = t(key);
        } else {
            elements[i].textContent = t(key);
        }
    }
}

// Initialize on page load
document.addEventListener('DOMContentLoaded', function() {
    applyLanguage();
});
